### ISSUE TITLE
coordinates in utils.get_healpix_centers

### ISSUE THREAD

**Issue by alfredcas** [gaia-unlimited/gaiaunlimited#11]
returns coord.SkyCoord(ra * u.deg, dec * u.deg) assuming wrong coordinate system. Results in different coordinate systems in dr3_rvs.ipynb (for GaiaVerse vs. GaiaUnlimited)

**Comment by TristanCantatGaudin** [comment]
It looks like the file **dr3-rvs-nk.h5**
was saved with values precomputed in Galactic healpix scheme. so using the same query method for both DR3RVSSelectionFunction and **E**DR3RVSSelectionFunction doesn't work. Foreseeing that all future precomputations will be in Equatorial (called 'Celestial' in healpy), here is my quick fix:

[2953b0b](https://github.com/gaia-unlimited/gaiaunlimited/commit/2953b0bba5580cd85a6e6fd119264aa6966d4452)
