### ISSUE TITLE
Make sure to change the verions of the main branch after a release in PyPI

### ISSUE THREAD

**Issue by agabrown** [gaia-unlimited/gaiaunlimited#13]

**Comment by mfouesneau** [comment]
we can use setuptools-scm to deal with versioning

**Comment by TristanCantatGaudin** [comment]
I bumped the version number to 0.2.0 in __init__.py

For some reason including __version__ in version.py and importing it in __init__.py caused the build to fail: https://github.com/gaia-unlimited/gaiaunlimited/commit/2fe42b55fe2c0d18350990de7ea0f6162cb6941a
