### ISSUE TITLE
scanning law angles (and possibly barycentric positions)

### ISSUE THREAD

**Issue by zpenoyre** [gaia-unlimited/gaiaunlimited#16]
At the moment we have a much simpler version of scanning law in gaia unlimited compared to the original scanninglaw (https://github.com/gaiaverse/scanninglaw) package - particularly the lack of scanning angles.

It would also be great to have barycentric positions of the satellite returned by the function, such that all elements needed for the astrometry spread function, and more generally making synthetic Gaia observations, are included in the scanninglaw.

Finally (we've talked about this offline) but it would be really useful to have the nominal scanning law for the full duration of the survey for simulating future results.

(also the initialization of the package seems much slower than the gaiaverse version?)

**Comment by agabrown** [comment]
Can be closed. Scanlaw and parallax factors are included as part of the binary selection function tools.
