### ISSUE TITLE
Need a centralized repo for datafiles

### ISSUE THREAD

**Issue by mfouesneau** [gaia-unlimited/gaiaunlimited#31]
https://github.com/gaia-unlimited/gaiaunlimited/blob/e5e44c5a93eb8a3a22de9138a10bd66946609c3a/src/gaiaunlimited/selectionfunctions/surveyTCG.py#LL73C53-L73C53

**Comment by TristanCantatGaudin** [comment]
All non-ESA files uploaded to Zenodo:

Data for emprical selection function paper: https://zenodo.org/record/8063930

Legacy files for the GaiaUnlimited tools: https://zenodo.org/record/8300616
