### ISSUE TITLE
Installation and Compatibility with Different Operating Systems.

### ISSUE THREAD

**Issue by MCruzReyes** [gaia-unlimited/gaiaunlimited#34]
I am not sure, but it seems that the [GaiaUnlimited](https://gaiaunlimited.readthedocs.io/en/latest/install.html) tools are not compatible with Windows. However, this is not explained in the documentation. 

It is not compatible, because one of the libraries that are needed ([healpy](https://pypi.org/project/healpy/)) is not compatible with Windows.

The issue appears when I run the following command on Windows
`pip install gaiaunlimited`

the issues does not appear on Linux

Error:
```
ERROR: Failed building wheel for healpy
Failed to build healpy
ERROR: Could not build wheels for healpy, which is required to install pyproject.toml-based projects

```
Python version:
Python 3.9.7

Operative system:
Windows 10

**Comment by mfouesneau** [comment]
This error is from Healpy, not Gaia Unlimited.

**Comment by agabrown** [comment]
True, but let's see if we can do something to address this

**Comment by TristanCantatGaudin** [comment]
The documentation now mentions that the package can be installed inside a Google Colab notebook (e.g. ``!pip install gaiaunlimited``) which might help users who have issues with local installation.

**Comment by mfouesneau** [comment]
Healpy is aware of this issue: https://github.com/healpy/healpy/issues/25

**Comment by TristanCantatGaudin** [comment]
Unfortunately no alternative so far, although the colab option does work well.

We keep debating whether to switch to astropy's healpix implementation, but currently it doesn't have the plotting capabilities of healpy.

**Comment by agabrown** [comment]
Given the above discussion, this will not be done.
