### ISSUE TITLE
Improve availability of examples in the documentation

### ISSUE THREAD

**Issue by agabrown** [gaia-unlimited/gaiaunlimited#43]
This refers to
* Including more examples of the use of the various classes and function
* Including more basic examples of how to use a selection function

**Comment by TristanCantatGaudin** [comment]
I have split the documentation table of contents into two sections: one documenting the general use of the package, and a second one with more concrete example applications (new: RAVE, APOGEE, Gaia GSP-Spec). The collection of examples can grow while leaving the general documentation compact enough to not look intimidating.
