### ISSUE TITLE
Include hierarchical prior for subsample selection function

### ISSUE THREAD

**Issue by agabrown** [gaia-unlimited/gaiaunlimited#44]
Sebastian Ratzenböck made the suggestion to let the tool hierarchically estimate the selection probabilities. The idea is to start out with large counting bins and a flat prior for the binomial distribution parameters and then let the resulting posterior be the prior for a refined set of counting bins.

**Comment by mfouesneau** [comment]
SubsampleSF_HMLE_Tutorial.ipynb
