### ISSUE TITLE
return_sorted simple fix

### ISSUE THREAD

**Issue by zpenoyre** [gaia-unlimited/gaiaunlimited#9]
return_sorted keyword seems to throw exceptions for many - really simple fix to replace

`# first drastically cutdown snapshots to check by positional matching
            tidx = tree_fov.query_ball_point(
                query_coord_xyz, self.r_search, return_sorted=True
            )
            if len(tidx) == 0:
                return
            tidx = np.array(tidx)`

with

`# first drastically cutdown snapshots to check by positional matching
            tidx = tree_fov.query_ball_point(
                query_coord_xyz, self.r_search
            )
            if len(tidx) == 0:
                return
            tidx = np.sort(np.array(tidx))`

**Comment by mfouesneau** [comment]
Thanks agreed.
A different approach used in #6 that fixed it.

**Comment by zpenoyre** [comment]
cool - although if it's just for this people might prefer not to have to update their scipy (plenty of scope for other conflicts)
